from __future__ import annotations

import argparse
import json
import logging
import os
from collections.abc import Mapping
from pathlib import Path
from typing import Final

from apps.api.clients.supabase_runtime import (
    get_supabase_runtime_client,
)
from apps.api.repositories.concept_repository import (
    ConceptRepository,
)
from apps.api.repositories.retrieval_repository import (
    RetrievalRepository,
)
from apps.api.services.retrieval import (
    CITATION_QUALITY_WEIGHT,
    CONCEPT_ALIGNMENT_WEIGHT,
    DEFAULT_CANDIDATE_POOL_PER_DOMAIN,
    DEFAULT_MAX_CHUNKS_PER_SOURCE,
    DEFAULT_MIN_VECTOR_SIMILARITY,
    DEFAULT_TOKEN_BUDGET_PER_DOMAIN,
    DEFAULT_TOP_K_PER_DOMAIN,
    FROZEN_CONCEPT_AWARE_RETAINED,
    FROZEN_RETRIEVAL_EVALUATION_COMPLETE,
    HUMAN_RELEVANCE_WEIGHT,
    RETRIEVAL_VERSION,
    SOURCE_REPEAT_PENALTY,
    VECTOR_WEIGHT,
    QueryEmbeddingConfig,
    RetrievalConfig,
    RetrievalError,
    RetrievalOutputPaths,
    RetrievalService,
)

LOGGER = logging.getLogger(
    "wth.phase1.build_retrieval"
)

SCRIPT_VERSION: Final = "1.0.0"

DEFAULT_OUTPUT_DIRECTORY: Final = Path(
    "artifacts/phase1/retrieval"
)

DEFAULT_RETRIEVAL_EVALUATION_RESULTS: Final = Path(
    "artifacts/phase1/retrieval/"
    "retrieval_evaluation_results.json"
)

DEFAULT_RETRIEVAL_REPORT: Final = Path(
    "docs/evaluation/phase1_retrieval_report.md"
)

# Retained only as accepted compatibility arguments. Production Stage 3
# no longer reads any of these artifacts during retrieval.
DEFAULT_ACTIVE_BUNDLES: Final = Path(
    "artifacts/phase1/active/"
    "phase1_active_chunk_bundles.jsonl"
)
DEFAULT_EMBEDDING_MANIFEST: Final = Path(
    "artifacts/phase1/embeddings/"
    "embedding_manifest.json"
)
DEFAULT_QUERY_PROTOTYPES: Final = Path(
    "artifacts/phase1/embeddings/"
    "query_prototype_embeddings.jsonl"
)
DEFAULT_PASSAGE_PROTOTYPES: Final = Path(
    "artifacts/phase1/embeddings/"
    "passage_prototype_embeddings.jsonl"
)
DEFAULT_RETRIEVAL_QUESTIONS: Final = Path(
    "packages/eval/eval_questions.jsonl"
)


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Phase 14: retrieve concept-aware, "
            "domain-separated evidence from the frozen "
            "production Supabase corpus."
        )
    )

    parser.add_argument(
        "--project-root",
        type=Path,
        default=Path.cwd(),
    )

    parser.add_argument(
        "--question",
        required=True,
        help=(
            "User question to retrieve evidence for."
        ),
    )

    parser.add_argument(
        "--output-directory",
        type=Path,
        default=DEFAULT_OUTPUT_DIRECTORY,
    )

    parser.add_argument(
        "--retrieval-evaluation-results",
        type=Path,
        default=DEFAULT_RETRIEVAL_EVALUATION_RESULTS,
        help=(
            "Frozen Phase 14 retrieval evaluation artifact. "
            "It is validated as provenance but never regenerated "
            "by the Stage 3 runtime wrapper."
        ),
    )

    parser.add_argument(
        "--retrieval-report",
        type=Path,
        default=DEFAULT_RETRIEVAL_REPORT,
        help=(
            "Frozen Phase 14 retrieval report. It must exist "
            "but is not regenerated by the Stage 3 wrapper."
        ),
    )

    # Frozen configuration knobs are retained in the CLI so older command
    # shapes continue to parse. RetrievalService rejects non-frozen values.
    parser.add_argument(
        "--top-k-per-domain",
        type=int,
        default=DEFAULT_TOP_K_PER_DOMAIN,
    )

    parser.add_argument(
        "--candidate-pool-per-domain",
        type=int,
        default=DEFAULT_CANDIDATE_POOL_PER_DOMAIN,
    )

    parser.add_argument(
        "--token-budget-per-domain",
        type=int,
        default=DEFAULT_TOKEN_BUDGET_PER_DOMAIN,
    )

    parser.add_argument(
        "--max-chunks-per-source",
        type=int,
        default=DEFAULT_MAX_CHUNKS_PER_SOURCE,
    )

    parser.add_argument(
        "--min-vector-similarity",
        type=float,
        default=DEFAULT_MIN_VECTOR_SIMILARITY,
    )

    parser.add_argument(
        "--embedding-timeout-seconds",
        type=float,
        default=45.0,
    )

    parser.add_argument(
        "--embedding-max-attempts",
        type=int,
        default=4,
    )

    # Deprecated Stage 2/local-artifact Phase 14 inputs.
    # Accepted only for CLI compatibility; intentionally unused.
    parser.add_argument(
        "--active-bundles",
        type=Path,
        default=DEFAULT_ACTIVE_BUNDLES,
        help=argparse.SUPPRESS,
    )

    parser.add_argument(
        "--embedding-manifest",
        type=Path,
        default=DEFAULT_EMBEDDING_MANIFEST,
        help=argparse.SUPPRESS,
    )

    parser.add_argument(
        "--query-prototype-embeddings",
        type=Path,
        default=DEFAULT_QUERY_PROTOTYPES,
        help=argparse.SUPPRESS,
    )

    parser.add_argument(
        "--passage-prototype-embeddings",
        type=Path,
        default=DEFAULT_PASSAGE_PROTOTYPES,
        help=argparse.SUPPRESS,
    )

    parser.add_argument(
        "--retrieval-questions",
        type=Path,
        default=DEFAULT_RETRIEVAL_QUESTIONS,
        help=argparse.SUPPRESS,
    )

    parser.add_argument(
        "--replace",
        action="store_true",
        help=(
            "Replace Phase 14 request-specific artifacts. "
            "Frozen evaluation results/report are never replaced."
        ),
    )

    parser.add_argument(
        "--log-level",
        choices=(
            "DEBUG",
            "INFO",
            "WARNING",
            "ERROR",
        ),
        default="INFO",
    )

    return parser.parse_args()


def configure_logging(
    level: str,
) -> None:
    logging.basicConfig(
        level=getattr(
            logging,
            level,
        ),
        format=(
            "%(asctime)s %(levelname)s "
            "%(name)s %(message)s"
        ),
    )


def resolve(
    project_root: Path,
    path: Path,
) -> Path:
    if path.is_absolute():
        return path.resolve()

    return (
        project_root
        / path
    ).resolve()


def require_file(
    path: Path,
    description: str,
) -> None:
    if not path.is_file():
        raise RetrievalError(
            f"{description} does not exist: {path}"
        )


def require_mapping(
    value: object,
    description: str,
) -> dict[str, object]:
    if not isinstance(
        value,
        Mapping,
    ):
        raise RetrievalError(
            f"{description} must be an object."
        )

    result: dict[
        str,
        object,
    ] = {}

    for key, nested in value.items():
        if not isinstance(
            key,
            str,
        ):
            raise RetrievalError(
                f"{description} contains a non-string key."
            )

        result[
            key
        ] = nested

    return result


def load_json(
    path: Path,
) -> dict[str, object]:
    try:
        raw: object = json.loads(
            path.read_text(
                encoding="utf-8",
            )
        )
    except json.JSONDecodeError as exc:
        raise RetrievalError(
            f"Invalid JSON in {path}: {exc}"
        ) from exc

    return require_mapping(
        raw,
        f"JSON document {path}",
    )


def atomic_json(
    path: Path,
    value: Mapping[str, object],
) -> None:
    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    temporary = path.with_suffix(
        path.suffix + ".tmp"
    )

    temporary.write_text(
        json.dumps(
            value,
            indent=2,
            sort_keys=True,
            ensure_ascii=False,
            allow_nan=False,
        )
        + "\n",
        encoding="utf-8",
    )

    temporary.replace(
        path
    )


def request_output_paths(
    output_directory: Path,
) -> dict[str, Path]:
    return {
        "config": (
            output_directory
            / "retrieval_config.json"
        ),
        "evidence": (
            output_directory
            / "evidence_package.json"
        ),
        "manifest": (
            output_directory
            / "retrieval_manifest.json"
        ),
    }


def ensure_replace_policy(
    *,
    paths: Mapping[str, Path],
    replace: bool,
) -> None:
    if replace:
        return

    existing = [
        path
        for path in paths.values()
        if path.exists()
    ]

    if existing:
        raise RetrievalError(
            "Phase 14 request artifacts already exist. "
            "Use --replace: "
            + ", ".join(
                path.as_posix()
                for path in existing
            )
        )


def read_environment_file(
    path: Path,
) -> None:
    """Load simple KEY=VALUE entries without overriding the environment."""

    if not path.is_file():
        return

    for raw_line in path.read_text(
        encoding="utf-8",
        errors="ignore",
    ).splitlines():
        line = raw_line.strip()

        if (
            not line
            or line.startswith("#")
            or "=" not in line
        ):
            continue

        key, raw_value = line.split(
            "=",
            1,
        )

        key = key.strip()
        value = raw_value.strip()

        if (
            not key
            or key in os.environ
        ):
            continue

        if (
            len(value) >= 2
            and value[0] == value[-1]
            and value[0] in {
                "'",
                '"',
            }
        ):
            value = value[
                1:-1
            ]

        os.environ[
            key
        ] = value


def load_project_environment(
    project_root: Path,
) -> None:
    for path in (
        project_root / ".env",
        project_root / ".env.local",
        project_root
        / "apps"
        / "api"
        / ".env",
        project_root
        / "apps"
        / "api"
        / ".env.local",
    ):
        read_environment_file(
            path
        )


def gemini_api_key(
    project_root: Path,
) -> str:
    """Use Google's precedence when both API-key names are configured."""

    load_project_environment(
        project_root
    )

    google_key = os.getenv(
        "GOOGLE_API_KEY",
        "",
    ).strip()

    if google_key:
        return google_key

    gemini_key = os.getenv(
        "GEMINI_API_KEY",
        "",
    ).strip()

    if gemini_key:
        return gemini_key

    raise RetrievalError(
        "GOOGLE_API_KEY or GEMINI_API_KEY is not configured."
    )


def validate_frozen_evaluation(
    *,
    results_path: Path,
    report_path: Path,
) -> None:
    """Ground runtime retention-gate claims in the frozen Phase 14 artifacts."""

    require_file(
        results_path,
        "Frozen retrieval evaluation results",
    )

    require_file(
        report_path,
        "Frozen retrieval report",
    )

    evaluation = load_json(
        results_path
    )

    corpus_version = evaluation.get(
        "corpus_version"
    )

    if (
        corpus_version
        != "phase1_active_corpus_v1"
    ):
        raise RetrievalError(
            "Frozen retrieval evaluation corpus version changed."
        )

    config = require_mapping(
        evaluation.get(
            "config"
        ),
        "Frozen retrieval evaluation config",
    )

    expected_config: dict[
        str,
        object,
    ] = {
        "top_k_per_domain": (
            DEFAULT_TOP_K_PER_DOMAIN
        ),
        "candidate_pool_per_domain": (
            DEFAULT_CANDIDATE_POOL_PER_DOMAIN
        ),
        "token_budget_per_domain": (
            DEFAULT_TOKEN_BUDGET_PER_DOMAIN
        ),
        "max_chunks_per_source": (
            DEFAULT_MAX_CHUNKS_PER_SOURCE
        ),
        "min_vector_similarity": (
            DEFAULT_MIN_VECTOR_SIMILARITY
        ),
    }

    if config != expected_config:
        raise RetrievalError(
            "Frozen retrieval evaluation configuration changed."
        )

    concept_aware = require_mapping(
        evaluation.get(
            "concept_aware"
        ),
        "Frozen concept-aware retrieval metrics",
    )

    precision = concept_aware.get(
        "macro_precision_at_k"
    )

    coverage = concept_aware.get(
        "macro_concept_coverage"
    )

    mrr = concept_aware.get(
        "mrr"
    )

    if (
        precision != 1.0
        or coverage != 1.0
        or mrr != 1.0
    ):
        raise RetrievalError(
            "Frozen concept-aware retrieval metrics "
            "no longer match the retained configuration."
        )

    if not (
        FROZEN_RETRIEVAL_EVALUATION_COMPLETE
        and FROZEN_CONCEPT_AWARE_RETAINED
    ):
        raise RetrievalError(
            "Runtime retrieval service no longer reports "
            "the frozen Phase 14 retention gate as passed."
        )


def retrieval_config_document(
    *,
    config: RetrievalConfig,
    evaluation_results_path: Path,
    retrieval_report_path: Path,
) -> dict[str, object]:
    """Write a request-independent snapshot of the locked Phase 14 config."""

    return {
        "retrieval_version": (
            RETRIEVAL_VERSION
        ),
        "retrieval_mode": (
            "concept_aware"
        ),
        "corpus_version": (
            "phase1_active_corpus_v1"
        ),
        "config": config.as_dict(),
        "scoring": {
            "vector_similarity_weight": (
                VECTOR_WEIGHT
            ),
            "concept_alignment_weight": (
                CONCEPT_ALIGNMENT_WEIGHT
            ),
            "human_relevance_weight": (
                HUMAN_RELEVANCE_WEIGHT
            ),
            "citation_quality_weight": (
                CITATION_QUALITY_WEIGHT
            ),
            "source_repeat_penalty": (
                SOURCE_REPEAT_PENALTY
            ),
        },
        "frozen_evaluation": {
            "evaluation_complete": True,
            "concept_aware_retained": True,
            "retrieval_evaluation_results": (
                evaluation_results_path.as_posix()
            ),
            "retrieval_report": (
                retrieval_report_path.as_posix()
            ),
        },
    }


def run_phase14(
    *,
    project_root: Path,
    question: str,
    output_directory: Path,
    retrieval_evaluation_results_path: Path,
    retrieval_report_path: Path,
    config: RetrievalConfig,
    embedding_timeout_seconds: float,
    embedding_max_attempts: int,
    replace: bool,
) -> dict[str, object]:
    """Run Phase 14 artifact mode through the single RetrievalService."""

    project_root = (
        project_root.resolve()
    )

    output_directory = resolve(
        project_root,
        output_directory,
    )

    retrieval_evaluation_results_path = resolve(
        project_root,
        retrieval_evaluation_results_path,
    )

    retrieval_report_path = resolve(
        project_root,
        retrieval_report_path,
    )

    normalized_question = (
        question.strip()
    )

    if not normalized_question:
        raise RetrievalError(
            "Question must be non-empty."
        )

    validate_frozen_evaluation(
        results_path=(
            retrieval_evaluation_results_path
        ),
        report_path=(
            retrieval_report_path
        ),
    )

    paths = request_output_paths(
        output_directory
    )

    # Ensure a failed replace check occurs before Gemini or Supabase calls.
    ensure_replace_policy(
        paths=paths,
        replace=replace,
    )

    api_key = gemini_api_key(
        project_root
    )
    if not os.getenv("GOOGLE_API_KEY","",).strip():
        os.environ[
            "GOOGLE_API_KEY"
        ] = api_key

    client = (
        get_supabase_runtime_client()
    )

    retrieval_repository = (
        RetrievalRepository(
            client
        )
    )

    concept_repository = (
        ConceptRepository(
            client
        )
    )

    service = RetrievalService(
        retrieval_repository=(
            retrieval_repository
        ),
        concept_repository=(
            concept_repository
        ),
        embedding_config=(
            QueryEmbeddingConfig(
                api_key=api_key,
                timeout_seconds=(
                    embedding_timeout_seconds
                ),
                max_attempts=(
                    embedding_max_attempts
                ),
            )
        ),
    )

    manifest_output_paths = (
        RetrievalOutputPaths(
            retrieval_config=(
                paths[
                    "config"
                ].as_posix()
            ),
            evidence_package=(
                paths[
                    "evidence"
                ].as_posix()
            ),
            retrieval_evaluation_results=(
                retrieval_evaluation_results_path.as_posix()
            ),
            retrieval_report=(
                retrieval_report_path.as_posix()
            ),
        )
    )

    LOGGER.info(
        "Phase 14 starting: retrieval_version=%s",
        RETRIEVAL_VERSION,
    )

    result = service.retrieve(
        question=normalized_question,
        config=config,
        output_paths=(
            manifest_output_paths
        ),
    )

    output_directory.mkdir(
        parents=True,
        exist_ok=True,
    )

    config_document = (
        retrieval_config_document(
            config=config,
            evaluation_results_path=(
                retrieval_evaluation_results_path
            ),
            retrieval_report_path=(
                retrieval_report_path
            ),
        )
    )

    evidence_document = (
        result.evidence_package.model_dump(
            mode="python",
            by_alias=True,
        )
    )

    manifest_document = (
        result.manifest.model_dump(
            mode="python",
            by_alias=True,
        )
    )

    atomic_json(
        paths["config"],
        config_document,
    )

    atomic_json(
        paths["evidence"],
        evidence_document,
    )

    atomic_json(
        paths["manifest"],
        manifest_document,
    )

    activation = (
        result.evidence_package.query_activation
    )

    LOGGER.info(
        "Phase 14 retrieval complete"
    )

    LOGGER.info(
        "Active concepts: %s",
        ", ".join(
            activation.active_concepts
        )
        if activation.active_concepts
        else "(none)",
    )

    LOGGER.info(
        "Question unsupported by frozen concepts: %s",
        activation.unsupported,
    )

    for domain in (
        "science",
        "advaita",
        "samkhya",
    ):
        domain_result = (
            result.evidence_package.domains[
                domain
            ]
        )

        LOGGER.info(
            "%s evidence_count=%d estimated_tokens=%d "
            "unique_sources=%d",
            domain,
            domain_result.evidence_count,
            domain_result.estimated_tokens,
            domain_result.unique_source_count,
        )

    LOGGER.info(
        "Frozen retrieval evaluation retained: %s",
        result.manifest.exit_gate.concept_aware_retained,
    )

    LOGGER.info(
        "Evidence package: %s",
        paths["evidence"],
    )

    LOGGER.info(
        "Retrieval manifest: %s",
        paths["manifest"],
    )

    return manifest_document


def main() -> int:
    arguments = parse_arguments()

    configure_logging(
        arguments.log_level
    )

    config = RetrievalConfig(
        top_k_per_domain=(
            arguments.top_k_per_domain
        ),
        candidate_pool_per_domain=(
            arguments.candidate_pool_per_domain
        ),
        token_budget_per_domain=(
            arguments.token_budget_per_domain
        ),
        max_chunks_per_source=(
            arguments.max_chunks_per_source
        ),
        min_vector_similarity=(
            arguments.min_vector_similarity
        ),
    )

    try:
        run_phase14(
            project_root=(
                arguments.project_root
            ),
            question=(
                arguments.question
            ),
            output_directory=(
                arguments.output_directory
            ),
            retrieval_evaluation_results_path=(
                arguments.retrieval_evaluation_results
            ),
            retrieval_report_path=(
                arguments.retrieval_report
            ),
            config=config,
            embedding_timeout_seconds=(
                arguments.embedding_timeout_seconds
            ),
            embedding_max_attempts=(
                arguments.embedding_max_attempts
            ),
            replace=(
                arguments.replace
            ),
        )

    except RetrievalError:
        LOGGER.exception(
            "Phase 14 retrieval failed"
        )
        return 1

    return 0


__all__ = [
    "DEFAULT_OUTPUT_DIRECTORY",
    "DEFAULT_RETRIEVAL_EVALUATION_RESULTS",
    "DEFAULT_RETRIEVAL_REPORT",
    "RETRIEVAL_VERSION",
    "RetrievalConfig",
    "RetrievalError",
    "gemini_api_key",
    "run_phase14",
    "validate_frozen_evaluation",
]


if __name__ == "__main__":
    raise SystemExit(
        main()
    )
